### ISSUE TITLE
certbot_agree_tos is not documented or has no default

### ISSUE THREAD

**Issue by chris968** [usegalaxy-eu/ansible-certbot#13]
The role fail to run because the `certbot_agree_tos` is not documented or has no default,  I had to figure out myself to set the variable to `--agree-tos` on my host variables.

**Comment by hexylena** [comment]
This is not documented because the role is mostly only used by people following a specific training material. It would make sense to add an empty default, but, it is intentional that it does not default to `--agree-tos`, as taking manual action is important.

**Comment by chris968** [comment]
ok, sound strange but a least you aware of.

**Comment by hexylena** [comment]
No, let's keep it open. It should be documented. Hopefully we can get to that soon. I appreciate you filing this!
